x-debug: &debug-environments
  DEBUG: ${DEBUG}

x-services: &services-environments
  PAYMENTSERVICE__URL: http://pay-api:8000
  BILLING_URL: http://billing:8000
  PAYAPI_URL_TEST: http://pay-api:8000
  BILLING_URL_TEST: http://billing:8000

x-telegram: &telegram-environments
  TELEGRAM__TOKEN: ${TELEGRAM__TOKEN}
  TELEGRAM__CHAT: ${TELEGRAM__CHAT}

x-allure: &allure-environmetns
  ALLURE__URL: http://allure:5050
  ALLURE__PROJECT_NAME: default

version: '3.5'
services:
  admin:
    env_file:
      - .env
    expose:
      - "8000"
    container_name: django
    environment:
      <<: *debug-environments
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - movies
    depends_on:
      - postgres
    volumes:
      - ./admin_panel/static/:/var/www/static:ro
    build: ./admin_panel/

  billing:
    container_name: billing
    image: billing
    networks:
      - movies
    environment:
      PAYMENTSERVICE__URL: http://pay-api:8000
      <<: *debug-environments
      <<: *services-environments

    depends_on:
      - postgres
      - redis

  pay-api:
    container_name: pay-api
    image: payapi
    networks:
      - movies
    environment:
      <<: *debug-environments
      <<: *services-environments
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_MAX_NET_RETRIES: ${STRIPE_MAX_NET_RETRIES}
      SUCCESS_URL: ${SUCCESS_URL}
      CANCEL_URL: ${CANCEL_URL}

  etl:
    container_name: etl
    restart: always
    image: etl
    networks:
      - movies
    depends_on:
      - postgres

  integration_test:
    container_name: integration_test
    image: integration_test
    networks:
      - movies
    environment:
      <<: *debug-environments
      <<: *services-environments
      <<: *telegram-environments
      <<: *allure-environmetns
    depends_on:
      - etl
      - pay-api
      - billing
      - postgres
      - stripe-cli
      - admin

  stripe-cli:
    container_name: stripe-cli
    image: stripe/stripe-cli
    environment:
      API-KEY: ${STRIPE_API_KEY}
      STRIPE_DEVICE_NAME: name
    command: "listen --api-key ${STRIPE_API_KEY} --forward-to pay-api:8000/webhook"
    networks:
      - movies

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - movies

  allure:
    image: "frankescobar/allure-docker-service:latest"
    container_name: allure
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: "TRUE"
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/projects:/app/projects
    networks:
      - movies


networks:
  movies:
    driver: bridge