x-debug: &debug-environments
  DEBUG: True

x-rabbit: &rabbit-environments
  RABBITMQ__USER: ${RABBITMQ__USER}
  RABBITMQ__PASSWORD: ${RABBITMQ__PASSWORD}
  RABBITMQ__SERVER: rabbitmq

version: '3.5'
services:
  admin:
    env_file:
      - .env
    expose:
      - "8000"
    container_name: django
    environment:
      <<: *debug-environments
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - movies
    depends_on:
      - postgres
    volumes:
      - ./admin_panel/static/:/var/www/static:ro
    build: ./admin_panel/

  billing:
    container_name: billing
    image: billing
    networks:
      - movies
    environment:
      <<: *debug-environments
      <<: *rabbit-environments
      PAY_URL: pay-api
    depends_on:
      - postgres
      - rabbitmq
      - redis

  pay-api:
    container_name: pay-api
    image: payapi
    networks:
      - movies
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_MAX_NET_RETRIES: ${STRIPE_MAX_NET_RETRIES}


  etl:
    container_name: etl
    restart: always
    image: etl
    build: ./etl/
    networks:
      - movies
    depends_on:
      - postgres

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.8-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__PASSWORD}
    networks:
      - movies

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - movies

networks:
  movies:
    driver: bridge