x-debug: &debug-environments
  DEBUG: True

version: '3.5'
services:
  admin:
    env_file:
      - .env
    expose:
      - "8000"
    container_name: django
    environment:
      <<: *debug-environments
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - movies
    depends_on:
      - postgres
    volumes:
      - ./admin_panel/static/:/var/www/static:ro
    build: ./admin_panel/

  billing:
    container_name: billing
    image: billing
    networks:
      - movies
    environment:
      <<: *debug-environments
      PAY_URL: pay-api
    depends_on:
      - postgres
      - redis

  pay-api:
    container_name: pay-api
    image: payapi
    networks:
      - movies
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_MAX_NET_RETRIES: ${STRIPE_MAX_NET_RETRIES}


  etl:
    container_name: etl
    restart: always
    image: etl
    networks:
      - movies
    depends_on:
      - postgres

  integration_test:
    container_name: integration_test
    image: integration_test
    networks:
      - movies
    environment:
      PAYAPI_URL_TEST: http://pay-api:8000
      BILLING_URL_TEST: http://billing:8000
    depends_on:
      - etl
      - pay-api
      - billing
      - postgres


  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - movies

networks:
  movies:
    driver: bridge