# Generated by Django 4.1.7 on 2023-03-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="duration",
            field=models.CharField(
                choices=[("month", "month"), ("day", "day")],
                default="month",
                max_length=7,
                verbose_name="duration",
            ),
        ),
    ]
