# Generated by Django 4.1.7 on 2023-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_product_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmworkproduct",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
