"""add payments

Revision ID: 954071a37f53
Revises: 2c10836afe2e
Create Date: 2023-03-11 20:56:51.380246

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "954071a37f53"
down_revision = "2c10836afe2e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("invoice_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column(
            "currency",
            sa.Enum("RUB", "USD", "EUR", name="currency_enum"),
            nullable=True,
        ),
        sa.Column("pay_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
        sa.UniqueConstraint("id"),
        schema="users",
    )
    # op.drop_table('alembic_version')
    op.create_unique_constraint(None, "invoice", ["id"], schema="users")
    op.create_unique_constraint(None, "movie", ["id"])
    op.create_unique_constraint(None, "product", ["id"])
    op.create_unique_constraint(None, "product_movie_link", ["id"])
    op.create_unique_constraint(None, "role", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    op.create_unique_constraint(None, "user_product_link", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_product_link", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "role", type_="unique")
    op.drop_constraint(None, "product_movie_link", type_="unique")
    op.drop_constraint(None, "product", type_="unique")
    op.drop_constraint(None, "movie", type_="unique")
    op.drop_constraint(None, "invoice", schema="users", type_="unique")
    op.create_table(
        "alembic_version",
        sa.Column("version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("version_num", name="alembic_version_pkc"),
    )
    op.drop_table("payment", schema="users")
    # ### end Alembic commands ###
