"""Initial

Revision ID: 1d03191cd7f5
Revises: 
Create Date: 2023-03-05 17:15:25.478525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d03191cd7f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_index('filmwork_product_filmwork_id_612cc902', table_name='filmwork_product')
    op.drop_index('filmwork_product_product_id_9821efe8', table_name='filmwork_product')
    op.drop_table('filmwork_product')
    op.drop_table('filmwork')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmwork',
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='filmwork_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('filmwork_product',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('filmwork_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['filmwork_id'], ['filmwork.id'], name='filmwork_product_filmwork_id_612cc902_fk_filmwork_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='filmwork_product_product_id_9821efe8_fk_product_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='filmwork_product_pkey'),
    sa.UniqueConstraint('filmwork_id', 'product_id', name='filmwork_product_group_idx')
    )
    op.create_index('filmwork_product_product_id_9821efe8', 'filmwork_product', ['product_id'], unique=False)
    op.create_index('filmwork_product_filmwork_id_612cc902', 'filmwork_product', ['filmwork_id'], unique=False)
    op.create_table('product',
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='product_pkey')
    )
    # ### end Alembic commands ###
